### ISSUE TITLE
有考虑2月28天和润年的情况吗

### ISSUE THREAD

**Issue by shinygang** [hustcc/timeago.js#1]
有考虑2月28天和润年的情况吗

**Comment by hustcc** [comment]
考虑过的，并且是支持的，我一会再testcase中增加一个用例。

**Comment by hustcc** [comment]
![image](https://cloud.githubusercontent.com/assets/7856674/16907237/5a051350-4cf4-11e6-9049-5da1da96b8ab.png)
已经增加测试用例。
