### ISSUE TITLE
npm module without the universal module definition boilerplate

### ISSUE THREAD

**Issue by dashed** [hustcc/timeago.js#10]
Kudos for this library!

I'm wondering if there is a possibility for an npm module without the universal module definition (umd) boilerplate: https://github.com/hustcc/timeago.js/blob/a0f872529bdec6ef7a8e340a567b8bcf73b48cb6/src/timeago.js#L2-L7

**Comment by hustcc** [comment]
you mean like this:

``` js
(function (root, factory) {
    if (typeof exports === 'object') {
        module.exports = factory();

    } else if (typeof define === 'function' && define.amd) {
        define(factory);

    } else {
        root.eventUtil = factory();
    }
})(this, function() {
    // your module
});
```

or what ?

**Comment by dashed** [comment]
To clarify, I'm asking if there may be an npm module without the universal module definition wrapping code, so as to keep the library light when used with module bundlers like webpack or browserify.

Example:

``` js
var timeago = function(nowDate, defaultLocale) {
    // ...

};

module.exports = timeago;
```

---

This might require a change in how timeago.js is packaged for npm, browser, etc.

Feel free to close this issue if this is a wontfix.

**Comment by hustcc** [comment]
If just `module.exports = timeago;`, it will more tiny, but the library will can not be used with `scirpt` tag:

``` js
<script src="dist/timeago.min.js"></script>
```

so many user just use it with `script` to import it.
