### ISSUE TITLE
Incorrect plural forms in pl locale

### ISSUE THREAD

**Issue by greg-dev** [hustcc/timeago.js#100]
The current Polish translation needs some corrections, for example it shows "11 sekund**y** temu", ..., "19 sekund**y** temu" instead of "11 sekund temu", ..., "19 sekund temu". There are similar problems with other units of time, you can see it when running tests I've added in a separate PR https://github.com/hustcc/timeago.js/pull/99

**Comment by hustcc** [comment]
@jcubic locale `pl` was created by jcubic, maybe you can discuess here for the language.

I know nothing about pl. ^_^

**Comment by jcubic** [comment]
The fix in PR looks good.

**Comment by hustcc** [comment]
@jcubic OK~
