### ISSUE TITLE
can't render some timedata correctly

### ISSUE THREAD

**Issue by bonesoul** [hustcc/timeago.js#103]
`<span class="timeago" datetime="Tue Jan 31 2017 00:47:58 GMT+0300 (Turkey Standard Time)" data-popup="tooltip" data-placement="bottom" data-original-title="31 Ocak 2017 00:47">2 days ago</span>
`  => renders "2 days ago"

`<span class="timeago" datetime="Sat Jan 28 2017 01:06:12 GMT+0300 (Turkey Standard Time)" data-popup="tooltip" data-placement="bottom" data-original-title="28 Ocak 2017 01:06">just now</span>
` =>renders "just now"

**Comment by hustcc** [comment]
npm v2.0.5 is OK.

**Comment by bonesoul** [comment]
when should we expect a release?

**Comment by hustcc** [comment]
release v2.0.5 on github.

**Comment by bonesoul** [comment]
hopefully we can also get a bower release soon too.

**Comment by hustcc** [comment]
bower v2.0.5 done.
