### ISSUE TITLE
Certain timestamps cause busy loops when automatically rendered

### ISSUE THREAD

**Issue by pbarger** [hustcc/timeago.js#104]
When certain timestamps are rendered by timeago's `render()` function, the delta between the timestamp and the current time that it calculates in `diffSec()` and passes to `nextInterval()` results in a timeout value larger than the effective upper limit for major browsers' `setTimeout()` implementation according to the [MDN docs](https://developer.mozilla.org/en-US/docs/Web/API/WindowTimers/setTimeout#Maximum_delay_value). This results in the browser firing the timeout immediately instead of after the intended delay and, since the function called after the timeout (`doRender()`) registers another timeout with itself as the callback, creates a busy loop in the browser.

As an example, see the value `nextInterval()` returns for the two dates below (roughly a month apart):

```javascript
> diffSec("2016-12-01T12:00:12Z", "2017-01-05T12:00:00Z")
3023988
> nextInterval(3023988)
2232013
> nextInterval(3023988) * 1000
2232013000
```

That 2232013000 value gets passed to `setTimeout()`, and the docs linked above describe what happens in such a situation:

> Browsers including Internet Explorer, Chrome, Safari, and Firefox store the delay as a 32-bit signed integer internally. This causes an integer overflow when using delays larger than 2147483647, resulting in the timeout being executed immediately.

Limiting this value with `Math.min()` to anything less than or equal to 2147483647 fixes this:

```javascript
  }, Math.min(nextInterval(diff) * 1000, 0x7FFFFFFF));
```

Plunker link with an example (using a copy-pasted and modified version of timeago): https://plnkr.co/edit/2nlfb8eWusa3yS1zuW47

(Originally found via https://gitlab.com/gitlab-org/gitlab-ce/issues/25132)

**Comment by hustcc** [comment]
Thank you for your issue. I will fixed it soon.

**Comment by hustcc** [comment]
npm v2.0.5 will be OK. Very thanks for issue.

Happy China's new year. :1st_place_medal:
