### ISSUE TITLE
Optimizations for using in components

### ISSUE THREAD

**Issue by breezewish** [hustcc/timeago.js#109]
When this library is used in components with life-cycles (e.g. react), capabilities of unregistering a single relative time instance is critical.

Current implementations have several disadvantages in such circumstances:

1. Does not support canceling timer for a singular DOM in a timeago instance. Instead all timers in the instance are cancelled. Because of this, we need to create a timeago instance for every single relative time instead of create one and share, which is really slow when there are many relative times to display (e.g. long lists).

2. Does not share member functions across timeago instances so that every timeago instance needs more memory, which makes it even worse --> Please use prototypes to eliminate the memory cost.

**Comment by hustcc** [comment]
Is [timeago-react](https://github.com/hustcc/timeago-react) can help ?

1. I don't know how cancel the timer for just one DOM node, maybe need a map to save something.

2. Done it with prototypes before, but will increase some file size, but not very big, I will redo it, also welcome for you pr.

**Comment by likerRr** [comment]
@hustcc @breeswish I added prototypes support in #110. Please, review it. 

For now `doRender` member is put in prototype too, because I think it could be better optimized before moving it to private members. For example:
1. Do we really need `cnt` parameter? As far as I see it doesn't make any sence. @hustcc , correct me if I'm wrong.
2. Do we really need 'k' prefix [here](https://github.com/hustcc/timeago.js/blob/master/src/timeago.js#L124)?
3. If we move it to privates, then parameter list will grow from 4 to 6, because we need move `this.nowDate` and `this.defaultLocale` out of body to parameters.

So, I believe, for now we can leave this method live in prototype as it is and make a single issue for optimizing just `render` and `doRender` methods later.

**Comment by hustcc** [comment]
#110 for optimizations.

**Comment by likerRr** [comment]
@hustcc please, note, that #110 doesn't include dist files, and it also adds additional 0.16kb to minified version (I checked it locally)

**Comment by hustcc** [comment]
I review the code, there has no meaning of the timer key in array, so we remove the code about.

**Comment by likerRr** [comment]
@hustcc will you make it?

**Comment by hustcc** [comment]
OK. [here](https://github.com/hustcc/timeago.js/commit/077965f5abf88078b16e9390e4e46944826fa1da#diff-374bc7657a5d9aae4ec99e137199aafc):

1. remove the `cnt`.
2. use array, `timer = []`.
3. in `cancel`, use for loop.

**Comment by likerRr** [comment]
In #111 I tried to add support for cancellable timers, the idea is:
1. Add map of nodes and timers: `timerId` => `node`
2. Clear timer and delete it from the map by passing node's reference to `cancel` method.

details are inside the pr

**Comment by hustcc** [comment]
@breeswish Is pr #111 can satisfy you need ?

**Comment by breezewish** [comment]
Great work! @likerRr 

I guess the time complexity of canceling a single timer can be improved from O(n) to O(1): by (additionally) storing the timer id to the node itself we could lookup timer id faster. However it may bring potential memory leak in old browsers (need more research on this). Ideas?

**Comment by likerRr** [comment]
@breeswish do you mean using [datasets](https://developer.mozilla.org/ru/docs/Web/API/HTMLElement/dataset)? How can it cause memory leak?

**Comment by breezewish** [comment]
Only in (very) old browsers which doesn't support datasets, e.g. IE 6. LOL

**Comment by hustcc** [comment]
@likerRr  Save in datasets maybe better then object.

1. O(n) to O(1)
2. No need to to judge whether they are the same nodes exactly (node1 === node2).
3. When use real-time render, we should set the date into node attribute or datasets, and dependent on DOM attribute or datasets.

**Comment by likerRr** [comment]
@hustcc I updated the #111 . Please review and  I think you can optimize it

**Comment by hustcc** [comment]
OK~

**Comment by hustcc** [comment]
@breeswish 

```js
import timeago from "timeago.js"

timeago.cancel(); // cancel all the real-time
timeago.cancel(node); // cancel a single node (native node or jq node)'s real-time render.
```
When start a timer, will save timer's id(int) into data-tid, and when `cancel` one node, will read the attribute `date-tid`, then clearInterval it.

Can this will be OK ? or other suggestions.

**Comment by breezewish** [comment]
I think it's good enough :)
