### ISSUE TITLE
11 days instead of 1 week

### ISSUE THREAD

**Issue by bytestream** [hustcc/timeago.js#119]
Is it possible to use ````11 days```` instead of ````1 week```` for example?

````js
timeago.register('custom', function(number, index) {
    // index = 8
    // number = 1
});
````

**Comment by hustcc** [comment]
Can not do like this.

If add a parameter into locale funcion like:

```js
timeago.register('custom', function(number, index, total_sec) {
    // use 3 parameters to format date
});
```

Then you can code your own format function.

**Comment by bytestream** [comment]
That would work. Want me to submit a PR?

**Comment by hustcc** [comment]
ok, just do it, include README, and should be compatible with the exist locales.

**Comment by bytestream** [comment]
Done!

````js
timeago.register('local', function(number, index, total_sec) {
    // Convert weeks to days.
    if ([8,9].indexOf(index) !== -1) {
        total_sec = parseInt(total_sec / 86400);
    }
    
    return [ ... ];
});

**Comment by hustcc** [comment]
Next version will be v 3.0.0, with this feature.

**Comment by likerRr** [comment]
Good work, but as I see Readme was not updated

**Comment by hustcc** [comment]
`README_zh.md` was not updated.  I will do it later, and the test works for v3.0.0.
