### ISSUE TITLE
Why not build on top of the standard HTML <time> element?

### ISSUE THREAD

**Issue by simevidas** [hustcc/timeago.js#12]
You can read about the `<time>` element [here](https://css-tricks.com/time-element/). You could use the standard `datetime` attribute instead of `data-timeago`, and you could also make the library work on `<time>` elements with zero configuration.

**Comment by hustcc** [comment]
This is a good idea, bolow need to be considered:
1. browse supported or compatibility
2. Downward compatibility
3. can not add little code to keep tiny

thanks for suggestion, if you have free time, waiting for your pr. ^_^~

**Comment by RyanZim** [comment]
As for browser support: http://caniuse.com/#feat=html5semantic.

**Comment by hustcc** [comment]
@simevidas @RyanZim I will learn for it. If you has some code, welcome to pull a request. ^_^~
