### ISSUE TITLE
疑问

### ISSUE THREAD

**Issue by stylejinmu** [hustcc/timeago.js#129]
src/timeago.js
1. 第44行的if判断是否可以去掉？
2. 第146行 0x7FFFFFFF 选这个数的标准是？转换成天数约为24.86天，不太明白！

**Comment by hustcc** [comment]
toDate 方法没有加完整的 testcase，目前来看好像第 44 行可以删除。

0x7FFFFFFF 是 setTimeout 的官方标准，如果时间超过 0x7FFFFFFF，会导致异常。https://github.com/hustcc/timeago.js/issues/104
