### ISSUE TITLE
Issue with 11..19 and n1 numbers and polish locale

### ISSUE THREAD

**Issue by jcubic** [hustcc/timeago.js#13]
I've created Polish locale (will create PR) but have problems. In polish 
"1 month" ago is "1 miesiąc temu"
"%s months ago" is "%s miesięce temu"
but for numbers 11..19, 21 31, ..., 91 is "%s miesięcy temu"

and there is no way to have this locale without modification of the library. Maybe locale be a function that accept number and unit like:

``` javascript
function locale(number, unit) {
   var str = number.toString();
   if (unit == 'hours') {
       if (number == 1) {
          return ['1 godzinę temu', 'za 1 godzinę'];
       } else if (str.length == 2 && str[0] == "1" || number % 10 == 1) {
          return ['%s godzin temu', 'za %s godzin'];
      } else {
        return ['%s godziny temu', 'za %s godziny'];
      }
  }
}
```

and the code can detect if locale is function or array.

**Comment by hustcc** [comment]
@_@, ^=_=^
so function locale should be allowed, or the only way of locale is function？

**Comment by jcubic** [comment]
I think it should be allowed, so the old locale will work without the need to covert them to functions.

**Comment by hustcc** [comment]
OK, It can only be this way. Polish is a very specia language ^_^~

You can just do it, but keep the library little, and the `tests/locales_test.js` must be updated also.

**Comment by hustcc** [comment]
In fact, the locales were added in 2 days (today and yesterday)， so I think the locales rule can be updated. The rules now `is not very prefact`, it can be:
1. all locales can be `independent module`;
2. `timeago.register('locale_name', locale_func)`, the locale_func can be require from 1 ;
3. the build in locales(en, zh_CN) can modified to `function`.

If change the locales rule to above, the library maybe more tiny and prefact.

**Comment by hustcc** [comment]
just have a look https://github.com/hustcc/timeago.js/commit/5c834b3a1ac51c4fd990d3c961d1870c2228a4b3. @NicoJuicy @paulcmal @CreativeSparkStudios @jcubic

update the locales, use `locale function`. and all locale.js should be a javascript module.

``` js
// register
timeago.register('da', require('timeago.js/locales/da'));

// then use it
timeago.format(date, 'da');
```

the locales rule more prefact, and the library from 2.5kb to 2.1 kb. ^_^~
