### ISSUE TITLE
Please Release New Version

### ISSUE THREAD

**Issue by ali-master** [hustcc/timeago.js#135]
Hi,

if you can, Please Release new version, because in current version, Persian Locale is not aviable for use.

Thanks to anyway.

**Comment by hustcc** [comment]
I will release new version after the auto-render tested manually.

automation test in virtual dom environment.

**Comment by ali-master** [comment]
So can you give me a release date?

**Comment by hustcc** [comment]
today night, I am on the bus now😅

**Comment by ali-master** [comment]
ooooh, Very thanks. 
I hope success for you,

**Comment by hustcc** [comment]
timeago.js@3.0.2 done.
