### ISSUE TITLE
Defining a timezone

### ISSUE THREAD

**Issue by devinmatte** [hustcc/timeago.js#136]
I can't seem to find documentation that states that this exists. But I have a problem right now, where my server records in UTC, but the client could be an different timezone, and it will compare the timestamp from UTC to their current. Which causes problems with timestamps appearing as "in 3 hours" when in reality they were 23 minutes ago. I know I can compare the client time to UTC and subtract the difference. But I would like to avoid that if there is a built in solution I'm just not aware of?

**Comment by hustcc** [comment]
This is same with issue #122
