### ISSUE TITLE
这个能不能转成JScript？

### ISSUE THREAD

**Issue by laoqiuqiu** [hustcc/timeago.js#141]
我想在windows环境下调用，但是运行错误，能不能帮忙转到Jscript，谢谢！

**Comment by hustcc** [comment]
windows 环境也可以使用 JavaScript 的吧？

**Comment by laoqiuqiu** [comment]
javascript不行，得是jscript，有些javascript的特性jscript没有。

**Comment by hustcc** [comment]
jscript 用来开发什么？跟js什么关系？

**Comment by laoqiuqiu** [comment]
https://en.wikipedia.org/wiki/JScript

用于Windows Script Host，作用类似vbscript。

**Comment by hustcc** [comment]
那这个可以另开一个项目，自己翻译一下吧。
