### ISSUE TITLE
写了一个vue的版本，怎么pr进来

### ISSUE THREAD

**Issue by fanpenghuix** [hustcc/timeago.js#148]
https://github.com/cdoneshot/timeago-vue

**Comment by hustcc** [comment]
需要怎么 pr 进来？加一个链接吗？可以加到首页地址里面。

另外，给你拉到一个私有项目中来了！

**Comment by fanpenghuix** [comment]
没在首页看到有vue版本，本来想在你的项目新开一个vue版本的分支，直接pr，你统一来发布到npm.原来已经有了

**Comment by hustcc** [comment]
目前做的这个私有项目也是另外一个朋友写的，但是一直都是半成品状态，所以还没有发布出去！
