### ISSUE TITLE
How to import locales with "import syntax"?

### ISSUE THREAD

**Issue by ghost** [hustcc/timeago.js#149]
If I use

` import timeago from 'timeago.js';
`
How I can import a locale?

**Comment by hustcc** [comment]
import xx from 'timeago.js/locales/xx.js'

**Comment by pavloko** [comment]
It'd be great to add this to the docs. I wonder why you don't support other locales by default with syntax `timeago(null, 'de').format(new Date())`?

**Comment by hustcc** [comment]
Support all locales by default will make bundle larger.

**Comment by pavloko** [comment]
A valid point. I was thinking that Webpack/Rollup can optimize for this.

**Comment by hustcc** [comment]
You can have a try with a pr.

**Comment by pavloko** [comment]
Can't promise:) Thanks for the great lib!
