### ISSUE TITLE
timeago doesn't work for epoch with time zone

### ISSUE THREAD

**Issue by kingroryg** [hustcc/timeago.js#155]
Using the epoch value as `1524490129` which is equal to `Monday, April 23, 2018 6:58:49 PM GMT+05:30` ([check here](https://www.epochconverter.com/)) with timeago gives me weird answer.

```rb
var timeago = require("timeago.js");
timeago().format(1524490129);  
# gives 48 years ago (which is wrong)
```

**Comment by hustcc** [comment]
Try 1524490129 * 1000.
