### ISSUE TITLE
Docs are unclear to me

### ISSUE THREAD

**Issue by ppetree** [hustcc/timeago.js#157]
I've read the docs and viewed the demo code.

If I understand this correctly, the times that I need rendered are wrapped in <time></time> tags as in this example:
`<time class="strong single">when you opened the page</time>`

And to render timeago on a single element you call
`timeago().render($('.single'));`

What I fail to understand is how to get timeago to update on all elements of type <time> and especially those that are dynamically added as you would find in any feed. Do you have to append the new element to the nodes array?

```
function start_timeago(native) {
  var nodes = [];
	nodes = $('.timeago time');
	timeago().render(nodes);
}
```

Also, it doesn't look as though it can calculate timeago for divs with varying times (again, as you would find in a feed).

**Comment by hustcc** [comment]
You should call `timeago().render(element)` for the new elements those are dynamically added.

The element must conrtains attributes named `datetime`.
