### ISSUE TITLE
add word for describe month in zh-CN and zh-TW 

### ISSUE THREAD

**Issue by ghost** [hustcc/timeago.js#165]
In both [zh-CN](https://github.com/hustcc/timeago.js/blob/master/src/lang/zh_CN.js) and [zh-TW](https://github.com/hustcc/timeago.js/blob/master/src/lang/zh_TW.js) . we use ['%s 月前', '%s 月后'] and ['%s 月前', '%s 月後'] to show month ago and in month.
Do u think is it a good idea to add  个 after datetime format, so it will look like ['%s 个月前', '%s 个月后'] and ['%s 個月前', '%s 個月後'].
Buz when i read the doc especially for month, i misunderstood  "1月前" => 1月之前 (before January ) instead of  1月前 (one month ago).
If u think it's a good idea, i would like to have a PR for it.
I already timeago.js this in my project!!! it's awesome.

**Comment by hustcc** [comment]
You are right. You can send a pr for this.

**Comment by hustcc** [comment]
In v4.0.0, I will change the api:

```js
import { format, render, cancel, register } from 'timeago.js';

// format date to string
const str = format(date, locale);

// real time render
const tid = render(dom, locale);

cancel(tid); // cancel one task

cancel(dom); // cancel the dom

cancel(); // cancel all

// new locale
register('new_locale', localeFunc);
```

What do you think of this design?

**Comment by ghost** [comment]
LGTM!!!!
There is only one that i would like to modified is **cancel all**
> cancel(); // cancel all

I personally think cancelAll() will be more clear to understand.
Back to cancel(id), cancel(dom), dev  **have to  put** argument to tell what them want to cancel and invalid to use it with no argument.

At the end, it is just my little opinion if author have further idea or thought, i am willing to discuss with u!!!!!!!!

thx for this project :100:

**Comment by hustcc** [comment]
The more Api, the harder it is to understand.

Give 2 api for cancel, seem redundant.
