### ISSUE TITLE
npm run test show 'NODE_ENV' is not recognised as an internal or external command

### ISSUE THREAD

**Issue by ghost** [hustcc/timeago.js#169]
when running `npm test` in windows i face the problem like #162 
**NODE_ENV is not recognised as an internal or external command**
```
> NODE_ENV=babel jest --no-cache && npm run size && lint-md ./
'NODE_ENV' is not recognised as an internal or external command.....
```
my machine env
**environment : windows7
     node : v7.6.0**

but after i run the test  on my RedHat machine, it works!!!!

so i google it [NODE_ENV is not recognised as an internal or external command](https://stackoverflow.com/questions/40034690/node-env-is-not-recognised-as-an-internal-or-external-command/40036979), people met this problem maybe  the command varies from the unix system command that you are using.

i found a solution
- `npm install cross-env ` 

- **modified** the package.json by add **cross-env before NODE_ENV.....**
`"test": "cross-env NODE_ENV=babel jest --no-cache && npm run size && lint-md ./"`

if u think it's a good idea, i would like to PR for it by following

1. insert cross-env before NOE_ENV `cross-env NODE_ENV`

**Comment by hustcc** [comment]
Ok, you can give me a pr, thanks.
