### ISSUE TITLE
All languages needs to be registered

### ISSUE THREAD

**Issue by Bramzor** [hustcc/timeago.js#175]
Im trying to use timeago.js in Angular but have a hard time registering the locales because I cannot use require()

How can I register them all (or a selection) by using only import?

**Comment by Bramzor** [comment]
Found it, might be an idea to add it to the documentation
`import { nl as locale_NL } from 'timeago.js/lib/lang';`

**Comment by hustcc** [comment]
Thanks, I will add the document in README.

if you want import all locales, maybe you can:

`import 'timeago.js/dist/timeago.locales.min.js'`

**Comment by Bramzor** [comment]
Great library btw! I like the fact that it is small instead of having to import libraries that are a few MB just for the timeago feature. Thanks a lot!

**Comment by hustcc** [comment]
😄
