### ISSUE TITLE
No default export for ES6 module in 4.0.0-beta.2

### ISSUE THREAD

**Issue by accetone** [hustcc/timeago.js#180]
Get undefined when build with webpack 4

```javascript
import timeago from 'timeago.js';

console.log(timeago); // undefined
```

Work with import all syntax:

```javascript
import * as timeago from 'timeago.js';
```

So seems like default export missing.

**Comment by jayrbolton** [comment]
Also just found this the hard way, +1

**Comment by xilibro** [comment]
> ```js
> import * as timeago from 'timeago.js';
> ```

save my life

**Comment by hustcc** [comment]
@accetone @jayrbolton Should do something on your start kit.

e.g. If you are using typescript, set `compilerOptions.allowSyntheticDefaultImports = true` in your tsconfig.json.

**Comment by accetone** [comment]
@hustcc thanks for the reply. I'm sure that when I opened this issue the docs (at least on npm) said use default import which not work. Now the docs okay, so I will close.
