### ISSUE TITLE
Document differences with built-in Intl.RelativeTimeFormat

### ISSUE THREAD

**Issue by rightaway** [hustcc/timeago.js#182]
Could you add the differences between this and `Intl.RelativeTimeFormat` (available in latest JS engines) to documentation so that people starting new projects could compare and decide which to use? What functionality does this have that's missing from that?

And an official recommendation too, do you still suggest using this package now that Intl.RelativeTimeFormat is available or would you say to use that instead on platforms where available?

**Comment by stof** [comment]
`Intl.RelativeTimeFormat` provides only the equivalent of the `format` method of this package. It does not offer the updates of elements in the DOM based on a timer.
Also, the generated messages might not be exactly the same.

**Comment by stof** [comment]
also, `Intl.RelativeTimeFormat` does not perform the selection of the unit of the diff. So it is not even equivalent to `format`, but only to part of it (so a subset of the `formatDiff` internal function).

`Intl.RelativeTimeFormat` could be used in a modern version of timeago.js to avoid the need to maintain all the locales, that's all.

**Comment by hustcc** [comment]
hah, maybe `timeago.js` can be a polyfill of `Intl.RelativeTimeFormat`.

**Comment by stof** [comment]
well, timeago.js would rather be something build on top of Intl.RelativeTimeFormat in the future (or today with a polyfill), responsible for selecting the relevant diff to format.

**Comment by hustcc** [comment]
format is for polyfill. render is based on polyfill.😂😂😂
