### ISSUE TITLE
Add `@types/jquery` as dependency

### ISSUE THREAD

**Issue by samuelmeuli** [hustcc/timeago.js#185]
I am using `timeago.js` in a TypeScript project. When compling the code, I get the following error:

```
$ tsc --noEmit
node_modules/timeago.js/timeago.d.ts:1:23 - error TS2688: Cannot find type definition file for 'jquery'.

1 /// <reference types="jquery" />
                        ~~~~~~
```

Adding `@types/jquery` as a `dependency` instead of a `devDependency` in this library should fix this problem. This is also what was suggested in an [earlier comment](https://github.com/hustcc/timeago.js/pull/107#issuecomment-282638879).

**Comment by hustcc** [comment]
add as peer dependence is better.

**Comment by tofra** [comment]
Is your error solved with this fix @samuelmeuli ?

**Comment by samuelmeuli** [comment]
Yes, it is, thanks!

**Comment by hustcc** [comment]
@tofra add `@types/jquery` into your package.json.
