### ISSUE TITLE
Should I solve a puzzle to see direct download link of your plugin?

### ISSUE THREAD

**Issue by dehghani-mehdi** [hustcc/timeago.js#194]
Please provide direct link to the ready-to-use js file (uncompressed and compressed)

**Comment by SiteSplat** [comment]
https://github.com/hustcc/timeago.js/blob/master/gh-pages/timeago.min.js

**Comment by cekvenich** [comment]
CDN: https://cdn.jsdelivr.net/gh/hustcc/timeago.js@3.0.0/dist/timeago.min.js

**Comment by hustcc** [comment]
Lib and dist file all in npm package.
