### ISSUE TITLE
Can't use timeago.locales.min.js

### ISSUE THREAD

**Issue by akaSybe** [hustcc/timeago.js#197]
Can't figured out how to use "timeago.locales.min.js" in ES environment.
Every time it crashes with 'timeago is not defined'.

None of these import before locales import help: `import "timeago.js"` or `import timeago from "timeago.js"`

I created demo repository:

https://github.com/akaSybe/rollup-timeago-import-trouble-example

**Comment by akaSybe** [comment]
This happens cause in ES environment `timeago` will never be registered as global variable, so in `timeago.locales.min.js` `global.timeago` just doesn't exist

**Comment by hustcc** [comment]
You should import timeago first, then import timegao.locales.

> this week will release new version 4.0.0.
