### ISSUE TITLE
Invalid types

### ISSUE THREAD

**Issue by Enngage** [hustcc/timeago.js#201]
Hi, 

From version 4 there seems to be an issue with types (or underlying code) for creating custom locales. For example, if you use this code from readme on version 4:

```typescript
const localeFunc = (number: number, index: number, totalSec: number): [string, string] => {
  // number: the timeago / timein number;
  // index: the index of array below;
  // totalSec: total seconds between date to be formatted and today's date;
  return [
    ['just now', 'right now'],
    ['%s seconds ago', 'in %s seconds'],
    ['1 minute ago', 'in 1 minute'],
    ['%s minutes ago', 'in %s minutes'],
    ['1 hour ago', 'in 1 hour'],
    ['%s hours ago', 'in %s hours'],
    ['1 day ago', 'in 1 day'],
    ['%s days ago', 'in %s days'],
    ['1 week ago', 'in 1 week'],
    ['%s weeks ago', 'in %s weeks'],
    ['1 month ago', 'in 1 month'],
    ['%s months ago', 'in %s months'],
    ['1 year ago', 'in 1 year'],
    ['%s years ago', 'in %s years']
  ][index];
};
// register your locale with timeago
register('my-locale', localeFunc);
```
It would not compile - the `index` previously used `number`, but now it takes `string` - why? 

The return type of  [string, string] is also incorrect - since you are returning array of arrays and not array with 2 values.

**Comment by hustcc** [comment]
1. What is the meaning of `It would not compile - the index previously used number, but now it takes string`?

2. The return type must be string array with length = 2, see the code `[index]`

**Comment by Enngage** [comment]
Hey, 

1) The signature of your `LocaleFunc` is 

```
(diff: number, idx: number, totalSec?: number) => [string, string];
```

However, in your readme you are passing `[string, string]` because you have array where one parameter is another array and the other is number (see `index` in your readme)

2) same as above :-)

**Comment by hustcc** [comment]
```ts
const localeFunc = (number: number, index: number, totalSec: number): [string, string] => {
  // number: the timeago / timein number;
  // index: the index of array below;
  // totalSec: total seconds between date to be formatted and today's date;
  return [
    ['just now', 'right now'],
    ['%s seconds ago', 'in %s seconds'],
  ][index] as [string, string];
};
```
The element of two-dimensional array is one-dimensional array.

typescript can not automatically derive the correct type.

**Comment by Enngage** [comment]
But you are casting `index` which is number to a `string`, right? You are using incorrect types which is why you have to use 'as'.
