### ISSUE TITLE
A version without built-in locales?

### ISSUE THREAD

**Issue by OrKoN** [hustcc/timeago.js#204]
Hi!

Thanks for working on the lib and a new version. I am wondering if it's possible to exclude built-in locales (en and ch_ZN) from the bundle. In my use case, I generate code bundles per language and I manually register the correct language in the build process. It'd be good to remove the built-in ones when a different language is used, to reduce the bundle size. Anyway, not a big deal, but what do you think?

Best regards,
Alex

**Comment by hustcc** [comment]
So 3 bundle: 

 - timeago.none.min.js
 - timeago.min.js
 - timeago.full.min.js

Also should ensure the commonjs has build-in locales. There seems to be no good way?

**Comment by OrKoN** [comment]
I am using ESM so not using the bundles published to npm. Probably, I didn't express it right: I'd like to exclude built-in locales from *my* bundle not the bundles published by timeago.js to npm. My code is like this:

```
import currentLocale from 'timeago.js/esm/lang/uk';
import { format, register } from 'timeago.js';
register('currentLocale', currentLocale);
```

I guess until the built-in locales are imported for the register function https://github.com/hustcc/timeago.js/blob/master/src/locales.ts#L8 my bundler cannot optimize and strip the built-in locales from my bundle.

**Comment by hustcc** [comment]
If remove build-in locales in `locases.ts`, the esm / commonjs will contains none build-in locales.

The plan is:

1. remove build-in locales in `locases.ts`
2. add `core.ts` to export api
3. export core api, and register build-in locales
