### ISSUE TITLE
format() on any input returns '50 years ago'

### ISSUE THREAD

**Issue by ghost** [hustcc/timeago.js#229]
https://codepen.io/nainardev/pen/NWNzMPX

**Comment by lolobosse** [comment]
Not if you use milliseconds (your input * 1000)

**Comment by ghost** [comment]
Unix time is already in ms

**Comment by lolobosse** [comment]
No yours is in sec:

![image](https://user-images.githubusercontent.com/5024077/94363197-e7f13e80-00c0-11eb-8f06-de5db62e5096.png)
