### ISSUE TITLE
Not all supported locales are exported together

### ISSUE THREAD

**Issue by caroqliu** [hustcc/timeago.js#238]
Five of the locales included in `lang/` are missing from `lang/index.ts`:

- cs
- da
- ka
- oc
- tk * This appears to be a special case since it wasn't released in 4.0.2

**Comment by hustcc** [comment]
default only contains en, zh

other langs, should be import by yourself.

**Comment by caroqliu** [comment]
I mean that they are missing from this file:
https://github.com/hustcc/timeago.js/blob/master/src/lang/index.ts

This causes them to be excluded from `full`:
https://github.com/hustcc/timeago.js/blob/7ebf670ec3d47af66b175225eb675354d12951c2/src/full.ts#L9-L11

Is this intentional?

**Comment by hustcc** [comment]
Sorry, can help with a pr?
