### ISSUE TITLE
CDN Error: Uncaught ReferenceError: exports is not defined

### ISSUE THREAD

**Issue by albrnick** [hustcc/timeago.js#243]
I've tried using the CDN version (since I just want to include this in my straight html page), but the CDN version:

<script src="//unpkg.com/timeago.js"></script>

gives the error:

Uncaught ReferenceError: exports is not defined

Thanks for your time!

**Comment by RatherLogical** [comment]
Try this: `https://unpkg.com/timeago.js/dist/timeago.min.js`
Then reference the lib with `timeago.format()`

**Comment by gregfr** [comment]
Thanks a lot!! This should be in the doc...

**Comment by hustcc** [comment]
add `browser: "dist/timeago.min.js"` in package.json will be ok.
