### ISSUE TITLE
Is this project actively maintained?

### ISSUE THREAD

**Issue by jmooring** [hustcc/timeago.js#260]
If yes, this issue blocks simple implementations:

<https://github.com/hustcc/timeago.js/issues/230> (with possible fix https://github.com/hustcc/timeago.js/pull/241)

**Comment by jmooring** [comment]
And the answer is... no.

**Comment by Petercopter** [comment]
Yes it is still actively maintained. Updated 3 months ago, as of this writing

**Comment by franciscop** [comment]
> Yes it is still actively maintained. Updated 3 months ago, as of this writing

I think you mean 4 years ago:

<img width="458" alt="image" src="https://github.com/hustcc/timeago.js/assets/2801252/7f15b208-b716-4acf-9454-43ea1aa07bcb">

**Comment by hustcc** [comment]
🙋🏻‍♂️
