### ISSUE TITLE
Error: ENOENT: no such file or directory, open 'E:\Projects\Code-Crafters\node_modules\timeago.js\src\format.ts'

### ISSUE THREAD

**Issue by soham1300** [hustcc/timeago.js#267]
How to solve this error show on terminal :

WARNING in ./node_modules/timeago.js/esm/format.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from 'E:\Projects\Code-Crafters\node_modules\timeago.js\src\format.ts' file: Error: ENOENT: no such file or directory, open 'E:\Projects\Code-Crafters\node_modules\timeago.js\src\format.ts'

**Comment by kimch321** [comment]
In my case, I resolved it by adding GENERATE_SOURCEMAP=false to the .env.local file and then restarting the server.

**Comment by kboul** [comment]
@kimch321 it works, thanks, but why is this required?
