### ISSUE TITLE
建议用 var timeago = new Timeago(); 这种写法

### ISSUE THREAD

**Issue by cocody** [hustcc/timeago.js#47]
表明这是个实例，而不是其他

**Comment by hustcc** [comment]
意思是用大写，还是加上 new ？

**Comment by breeswish** [comment]
Agree for using constructors. Current style is misleading and is bad for code review. Besides, using constructor & prototype saves memory because methods are shared instead of duplicated.

**Comment by hustcc** [comment]
I will make a 2.0 version for big changs, welcome to submit pr.
