### ISSUE TITLE
A space should be inserted between half-width characters and full-width characters

### ISSUE THREAD

**Issue by breezewish** [hustcc/timeago.js#60]
bad: `6月前`

good: `6 月前`

**Comment by breezewish** [comment]
Space between half-width and full-width characters is a commonly adapted habit, for example in products of Google, Microsoft, Adobe. In addition, most of typography tools (like Office word, Adobe InDesign) automatically add space. There is also a W3C draft standard recommended to add space: http://w3c.github.io/clreq/#mixed_text_composition_in_horizontal_writing_mode

**Comment by hustcc** [comment]
`6 月前` is the standard style, but that is for lots of content, for a tag, remove the blank maybe better, you can haveq a try. 

orw you register your style.

**Comment by breezewish** [comment]
You are right. It looks better to not having space in short tags. However I'm going to always add a space for unification purpose :P
