### ISSUE TITLE
Move locale as the first parameter for `timeago()`

### ISSUE THREAD

**Issue by breezewish** [hustcc/timeago.js#61]
It is much more common to changing locale compare to changing base time.

**Comment by hustcc** [comment]
the 2th parameter is from pr later, consider for compatibility.

**Comment by breezewish** [comment]
Yes its reasonable for compatibility consideration. Since you are going to release version 2, according to semantic version you can introduce some incompatible changes, for example, changes that fixing this issue 😆

**Comment by hustcc** [comment]
Thank you for suggestion.^_^
