### ISSUE TITLE
What's the reason of using definePlugin in webpack?

### ISSUE THREAD

**Issue by likerRr** [hustcc/timeago.js#72]
I don't see that you use [`process.env`](https://github.com/hustcc/timeago.js/blob/master/webpack.config.js#L6-L8) somewhere in [locales](https://github.com/hustcc/timeago.js/blob/master/src/timeago.locales.js), so what the reason of keeping `definePlugin`?

**Comment by hustcc** [comment]
There is no meaning for it, from the Internal Project which has used React.

remove it. :haircut:
