### ISSUE TITLE
Generate separate timeago.js with only english locale

### ISSUE THREAD

**Issue by ClemMakesApps** [hustcc/timeago.js#80]
It would be nice to have a generated `timeago.js` that only included the english as it's default locale. I am currently in a situation where I will not be using the chinese locale and would like to have them removed so that I can optimize the size of my third party dependencies. 

Imo, it would be easier to have this part of this repo rather than me having to maintain my own fork.

Something like `dist/timeago.en.js` with only english as the default locale would be perfect!

**Comment by hustcc** [comment]
In fact, build-in locales(en, cn) can be applied to most scenes, delete zh_CN can only reduce little filesize, less than the version header.

So if you need a version with none build-in locales, just for redule the filesize, I think delete the version maybe better and more helpful._^_^_

**Comment by ClemMakesApps** [comment]
Sure! That sounds like a good idea!

**Comment by hustcc** [comment]
So do not care about the build-in locales. This is the smallest timeago library In thw world.

**Comment by ClemMakesApps** [comment]
Yes. It would be great to have a version that has no default locales 👍

**Comment by hustcc** [comment]
Ok, do you have any solution ? 

gulp-wrap can do, but seems not perfect.

**Comment by ClemMakesApps** [comment]
Here are the options I think we have:
1. Remove all of the default locales from `timeago.js` (this would force everyone to load their own locale)
2. Generate new `timeago.nolocales.js` using something similar to `gulp-wrap` such that we can use pattern matching to remove the default locales found in `timeago.js`
3. Remove all the default locales from `timeago.js` and use that file to generate `timeago.nolocales.js`, then using webpack or gulp, bundle the english and chinese locale into `timeago.js`

@hustcc thoughts?

**Comment by hustcc** [comment]
If dist/timeago.js can solve your problem, use it is the best option.

default en and zh can satisfy 80% developer, maybe. If you remove zh just for saving 30 bytes filesize, I think it is unfair to so many developer in China, include me.

all locales can be required, but more convenient when it is default.

default locales are optimisticed in filesize, they are much more little than pack from require locale. I means the size of `timeago.nolocale.js + locales/en.js` will be bigger the dist/timeago.min.js which has two default locales.

**Comment by ClemMakesApps** [comment]
In that case, looks like the best solution would be to use some kind of pattern matching to remove the chinese locale to generate something like `timeago.en.js`.

And just to be clear, I think it's totally okay to have a `timeago.js` with a default in en and zh. I just wanted to lay out the options 😄
