### ISSUE TITLE
怎么都返回"刚刚"

### ISSUE THREAD

**Issue by ichynul** [hustcc/timeago.js#81]

**Comment by hustcc** [comment]
你是如何使用的？可以贴一下你的代码，我来看看~

**Comment by ichynul** [comment]
解决了，是版本不同的问题，data-timeago变成了datetime。
另外，可不可以不写datetime属性，直接替换里面的text 如:
`<span>2016-09-30 01:01:01<span>`
 =>
 `<span>13小时前<span>`

**Comment by hustcc** [comment]
是，1.x.x 和 2.x.x的变化比较大，详细可以看 [wiki](https://github.com/hustcc/timeago.js/wiki).

**Comment by hustcc** [comment]
其实建议的写法是：

``` html
<time datetime="2016-09-30 01:01:01"></time>
```

这样比较符合h5规范。
