### ISSUE TITLE
agoin is not defined

### ISSUE THREAD

**Issue by empirefox** [hustcc/timeago.js#88]

**Comment by likerRr** [comment]
@empirefox could you provide more info about the issue?
What have you done to receive it?

**Comment by empirefox** [comment]
I just use it with angular2 as a pipe, and it always gives me that error. The value used is 1476010244000. I search 'agoin' in source, it looks like 'agoin' is indeed not defined.
[https://github.com/hustcc/timeago.js/blob/master/src/timeago.js#L60](https://github.com/hustcc/timeago.js/blob/master/src/timeago.js#L60)

**Comment by empirefox** [comment]
Here is the code: [https://github.com/empirefox/ec-front/blob/master/src/app/core/pipes/ago.pipe.ts](https://github.com/empirefox/ec-front/blob/master/src/app/core/pipes/ago.pipe.ts)

**Comment by likerRr** [comment]
Hope, #89 will solve the issue

**Comment by hustcc** [comment]
Thank you. @likerRr @empirefox 

Published as v2.0.3, typo fixed and more locales included.
