### ISSUE TITLE
Usage in Chrome Extension

### ISSUE THREAD

**Issue by nickdex** [hustcc/timeago.js#94]
Can you advise me how to use this in a chrome extension?
I have included minified file in HTML but can't use npm to install.

**Comment by hustcc** [comment]
You can just download the `dist/timeago.js` file into your chrome extension project wordspace.

Then there is no need to use npm to install.

**Comment by hustcc** [comment]
Can help you ? If it has solved your problem, pls close the issue.

**Comment by nickdex** [comment]
Sorry I got caught up in project and forgot to reply. I ended up using jQuery timeago library for now. I'm planning on migrating to node so I'll use your library at that time.
