### ISSUE TITLE
Ignore "n seconds ago" and use "just now"

### ISSUE THREAD

**Issue by mariotacke** [hustcc/timeago.js#97]
Is there any way to configure the library to not show "12 seconds ago" but instead use "just now" for values up to 59 seconds? I find that showing the seconds tends to distract the user because it is constantly updated.

I could register my own locale with the same value for seconds and minutes, but that seems hacky and does not translate for other locales.

**Comment by hustcc** [comment]
You can write you own rules (or locale), such as https://github.com/hustcc/timeago.js/blob/master/locales/en_short.js.

```js
var test_local_dict = function(number, index) {
  // number: the timeago / timein number;
  // index: the index of array below;
  return [
    ['just now', 'right now'],
    ['%s seconds ago', 'in %s seconds'],
    ['1 minute ago', 'in 1 minute'],
    ['%s minutes ago', 'in %s minutes'],
    ['1 hour ago', 'in 1 hour'],
    ['%s hours ago', 'in %s hours'],
    ['1 day ago', 'in 1 day'],
    ['%s days ago', 'in %s days'],
    ['1 week ago', 'in 1 week'],
    ['%s weeks ago', 'in %s weeks'],
    ['1 month ago', 'in 1 month'],
    ['%s months ago', 'in %s months'],
    ['1 year ago', 'in 1 year'],
    ['%s years ago', 'in %s years']
  ][index];
};
```

Then register it.

```js
// register your locale with timeago
timeago.register('your_rule_name', test_local_dict);
// use the locale with timeago instance 
var timeagoInstance = new timeago();
timeagoInstance.format('2016-06-12', 'your_rule_name');
```

**Comment by hustcc** [comment]
the locale function format is: 
```js
function(number, index) {}
```

**number**: the diff seconds
**index**: the index of diff seconds, something useless
return **the formated string**.

**Comment by bytestream** [comment]
Was there a solution here that didn't involve loosing all the pre-defined translations?

**Comment by hustcc** [comment]
@bytestream What is you meaning ?

**Comment by bytestream** [comment]
Maybe I misunderstood, but if I define ````test_local_dict```` then I can change "n seconds ago" to "just now" for **one locale** (test_local_dict).

How do I change it for English, French, Chinese, Spanish, etc (list goes on) without editing all these files: https://github.com/hustcc/timeago.js/tree/master/locales?

**Comment by hustcc** [comment]
Editing all these files may be the unique way.

Every locale has it's own tranlation to express `just now`.
