### ISSUE TITLE
Taking too much CPU with jQuery

### ISSUE THREAD

**Issue by millette** [hustcc/timeago.js#98]
Found something very weird on Firefox 45.6.0 on Debian. Adding a few instance.render() with jQuery uses lots of CPU, although on Chromium things were reasonable.

I was able to bring down CPU usage using the following loop:
```
var timeagoInstance = new timeago()
var $timeago = $('.timeago')
var r
// timeagoInstance.render($timeago, 'fr')
for (r = 0; r < $timeago.length; ++r) {
  timeagoInstance.render($timeago[r], 'fr')
}
```

If instead of a for loop I use

```
timeagoInstance.render($timeago, 'fr')
```

Then CPU usage seems to explode.

**Comment by likerRr** [comment]
@millette Can you please add a plunkr with test code?

**Comment by millette** [comment]
I tried to use plunkr:
http://plnkr.co/edit/E1Ilev?p=preview (**updated link**)

<del>Any suggestions to include the timeago JavaScript (and ideally the language file too)? For now, my plunkr is working in Firefox but not in Chrome because of the JS mimetime from github.</del><ins>There, fixed it using <https://cdnjs.cloudflare.com/ajax/libs/timeago.js/2.0.4/timeago.min.js></ins>.

More importantly, I haven't reproduced the high cpu usage I reported. I'm checking if it's jquery 2.2.2 vs 2.2.4 or if it's the language.

**Comment by millette** [comment]
Now I'm pretty sure it was a problem due to jQuery 2.2.2 I was using. I've now switched to jQuery 2.2.4 and the problem disappeared.

**Comment by likerRr** [comment]
@millette it's quite strange. I tested with jquery2.2.2 and it doesn't increase CPU usage at all http://clip2net.com/s/3FNKP8t

**Comment by millette** [comment]
Hmm. Maybe it had something to do with my minifying... In any case, it's not an issue with timeago and as I figured it out, I stumbled on a fix on my end too.
